import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/header";

const fonty = Sora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Xypher",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fonty.className + " relative"}>
        <Navbar />
        <div className="mx-auto max-w-6xl">{children}</div>
      </body>
    </html>
  );
}
